...
...
...
For 3 new syscalls, we have these event numbers for them:
   SYS_GET_RAND 135
   SYS_LOCK_MUTEX 136
   SYS_UNLOCK_MUTEX 137
the ID of video mutex is VIDEO_MUTEX 0
the state of the lock in a mutex is either LOCKED 1 or UNLOCKED 0
...
...
add a new state: SUSPEND for processes suspended in mutex
...
...
A new data type mutex_t is declared and it has:
   an integer 'lock' that indicates the status of the mutex lock
   a queue 'suspend_que' which holds PID's of suspended processes
...
